### ISSUE TITLE
Creating empty Issue

### ISSUE THREAD

**Issue by GuguRD** [githubjeka/tracker-issues#10]
When I click on New Issue button on a Space and the form is show if I cancel by closing the form the Issue is created anyway and empty.

PS: I replaced the files from your merge request on official HumHub repo.

**Comment by githubjeka** [comment]
Ref https://github.com/githubjeka/tracker-issues/issues/4#issuecomment-297491009

> This is a feature called "Draft". Now, when you click "Create issue" will be created one draft issue, and you are updating already the data for this task in fact. Later it will be improved to autosave every N secоnds when you describe your issue. For example, Jetbrain Youtrack has this behavior.
