### ISSUE TITLE
error can't create new issue

### ISSUE THREAD

**Issue by joe2824** [githubjeka/tracker-issues#12]
I have following problem.
When I try to add a new issue I only get a error massage.

Here is the log error:
`yii\web\HttpException: Dieses Modul ist in diesem Content Container nicht aktiviert! in /home/joelklei/hub.ogdorheim.de/protected/humhub/modules/content/components/ContentContainerController.php:103 Stack trace: #0 /home/joelklei/hub.ogdorheim.de/protected/vendor/yiisoft/yii2/base/Object.php(107): humhub\modules\content\components\ContentContainerController->init() #1 /home/joelklei/hub.ogdorheim.de/protected/vendor/yiisoft/yii2/base/Controller.php(86): yii\base\Object->__construct(Array) #2 [internal function]: yii\base\Controller->__construct('issue', Object(tracker\Module), Array) #3 /home/joelklei/hub.ogdorheim.de/protected/vendor/yiisoft/yii2/di/Container.php(375): ReflectionClass->newInstanceArgs(Array) #4 /home/joelklei/hub.ogdorheim.de/protected/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('tracker\\control...', Array, Array) #5 /home/joelklei/hub.ogdorheim.de/protected/vendor/yiisoft/yii2/BaseYii.php(340): yii\di\Container->get('tracker\\control...', Array) #6 /home/joelklei/hub.ogdorheim.de/protected/vendor/yiisoft/yii2/base/Module.php(638): yii\BaseYii::createObject('tracker\\control...', Array) #7 /home/joelklei/hub.ogdorheim.de/protected/vendor/yiisoft/yii2/base/Module.php(591): yii\base\Module->createControllerByID('issue') #8 /home/joelklei/hub.ogdorheim.de/protected/vendor/yiisoft/yii2/base/Module.php(583): yii\base\Module->createController('create') #9 /home/joelklei/hub.ogdorheim.de/protected/vendor/yiisoft/yii2/base/Module.php(517): yii\base\Module->createController('issue/create') #10 /home/joelklei/hub.ogdorheim.de/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('tracker-issues/...', Array) #11 /home/joelklei/hub.ogdorheim.de/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) #12 /home/joelklei/hub.ogdorheim.de/index.php(25): yii\base\Application->run() #13 {main}`

**Comment by githubjeka** [comment]
Your user profile haven't got this module. Activate it your profile or choose a space by name when you create new issue.
