### ISSUE TITLE
Filter not working

### ISSUE THREAD

**Issue by freakms** [githubjeka/tracker-issues#16]
When i choose a filter in the overview of the tracker-issues, nothing will be shown. When I check "all" nothing will be shown. I have to load the overview again with klicking on the module in the space-menue.

**Comment by githubjeka** [comment]
The new search will be integrated with new versions ...

![image](https://user-images.githubusercontent.com/874234/37972032-0f16cab4-31e0-11e8-9fa2-93fd62b5218d.png)

p.s. sorry for the late reply

**Comment by freakms** [comment]
thanks!

Any Idea when in will be released?

**Comment by githubjeka** [comment]
after HumHub 1.3 release

**Comment by githubjeka** [comment]
Check new version - https://github.com/githubjeka/tracker-issues/releases/tag/v.0.1.2
