### ISSUE TITLE
Error when adding or edit issue

### ISSUE THREAD

**Issue by dannyrichardson** [githubjeka/tracker-issues#17]
{
    "url": "/humhub/index.php?r=tracker-issues%2Fissue%2Fcreate&sguid=17a8ebf2-595f-4a3b-9970-04ea3b9455a6",
    "status": 500,
    "response": "<pre>PHP Warning &#039;yii\\base\\ErrorException&#039; with message &#039;Invalid argument supplied for foreach()&#039; \n\nin /home/avvalphen/domains/avvalphen.org/public_html/humhub/protected/humhub/modules/content/models/Content.php:170\n\nStack trace:\n#0 /home/avvalphen/domains/avvalphen.org/public_html/humhub/protected/humhub/modules/content/models/Content.php(170): yii\\base\\ErrorHandler-&gt;handleError(2, &#039;Invalid argumen...&#039;, &#039;/home/avvalphen...&#039;, 170, Array)\n#1 /home/avvalp...",
    "textStatus": "error",
    "dataType": "html",
    "xhr": {
        "readyState": 4,
        "responseText": "<pre>PHP Warning &#039;yii\\base\\ErrorException&#039; with message &#039;Invalid argument supplied for foreach()&#039; \n\nin /home/avvalphen/domains/avvalphen.org/public_html/humhub/protected/humhub/modules/content/models/Content.php:170\n\nStack trace:\n#0 /home/avvalphen/domains/avvalphen.org/public_html/humhub/protected/humhub/modules/content/models/Content.php(170): yii\\base\\ErrorHandler-&gt;handleError(2, &#039;Invalid argumen...&#039;, &#039;/home/avvalphen...&#039;, 170, Array)\n#1 /home/avvalphen/domains/avvalphen.org/public_html/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(505): humhub\\modules\\content\\models\\Content-&gt;afterSave(true, Array)\n#2 /home/avvalphen/domains/avvalphen.org/public_html/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(461): yii\\db\\ActiveRecord-&gt;insertInternal(NULL)\n#3 /home/avvalphen/domains/avvalphen.org/public_html/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(643): yii\\db\\ActiveRecord-&gt;insert(true, NULL)\n#4 /home/avvalphen/domains/avvalphen.org/public_html/humhub/protected/humhub/modules/content/components/ContentActiveRecord.php(342): yii\\db\\BaseActiveRecord-&gt;save()\n#5 /home/avvalphen/domains/avvalphen.org/public_html/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(505): humhub\\modules\\content\\components\\ContentActiveRecord-&gt;afterSave(true, Array)\n#6 /home/avvalphen/domains/avvalphen.org/public_html/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(461): yii\\db\\ActiveRecord-&gt;insertInternal(NULL)\n#7 /home/avvalphen/domains/avvalphen.org/public_html/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(643): yii\\db\\ActiveRecord-&gt;insert(true, NULL)\n#8 /home/avvalphen/domains/avvalphen.org/public_html/humhub/protected/modules/tracker/controllers/services/IssueCreator.php(29): yii\\db\\BaseActiveRecord-&gt;save()\n#9 /home/avvalphen/domains/avvalphen.org/public_html/humhub/protected/modules/tracker/controllers/IssueController.php(67): tracker\\controllers\\services\\IssueCreator-&gt;createDraft(Object(humhub\\modules\\space\\models\\Space))\n#10 [internal function]: tracker\\controllers\\IssueController-&gt;actionCreate()\n#11 /home/avvalphen/domains/avvalphen.org/public_html/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)\n#12 /home/avvalphen/domains/avvalphen.org/public_html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\\base\\InlineAction-&gt;runWithParams(Array)\n#13 /home/avvalphen/domains/avvalphen.org/public_html/humhub/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\\base\\Controller-&gt;runAction(&#039;create&#039;, Array)\n#14 /home/avvalphen/domains/avvalphen.org/public_html/humhub/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\\base\\Module-&gt;runAction(&#039;tracker-issues/...&#039;, Array)\n#15 /home/avvalphen/domains/avvalphen.org/public_html/humhub/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\\web\\Application-&gt;handleRequest(Object(humhub\\components\\Request))\n#16 /home/avvalphen/domains/avvalphen.org/public_html/humhub/index.php(25): yii\\base\\Application-&gt;run()\n#17 {main}</pre>",
        "status": 500,
        "statusText": "Internal Server Error"
    },
    "html": "<pre>PHP Warning &#039;yii\\base\\ErrorException&#039; with message &#039;Invalid argument supplied for foreach()&#039; \n\nin /home/avvalphen/domains/avvalphen.org/public_html/humhub/protected/humhub/modules/content/models/Content.php:170\n\nStack trace:\n#0 /home/avvalphen/domains/avvalphen.org/public_html/humhub/protected/humhub/modules/content/models/Content.php(170): yii\\base\\ErrorHandler-&gt;handleError(2, &#039;Invalid argumen...&#039;, &#039;/home/avvalphen...&#039;, 170, Array)\n#1 /home/avvalp...",
    "error": {},
    "errorThrown": "Internal Server Error",
    "validationError": false
}

Other error:

{
    "url": "/humhub/index.php?r=tracker-issues%2Fissue%2Fedit&id=1&sguid=17a8ebf2-595f-4a3b-9970-04ea3b9455a6",
    "status": 500,
    "response": "<pre>Exception &#039;LogicException&#039; with message &#039;&#039; \n\nin /home/avvalphen/domains/avvalphen.org/public_html/humhub/protected/modules/tracker/controllers/services/IssueEditor.php:55\n\nStack trace:\n#0 /home/avvalphen/domains/avvalphen.org/public_html/humhub/protected/modules/tracker/controllers/IssueController.php(128): tracker\\controllers\\services\\IssueEditor-&gt;__construct(Object(tracker\\models\\Issue))\n#1 [internal function]: tracker\\controllers\\IssueController-&gt;actionEdit(&#03...",
    "textStatus": "error",
    "dataType": "html",
    "xhr": {
        "readyState": 4,
        "responseText": "<pre>Exception &#039;LogicException&#039; with message &#039;&#039; \n\nin /home/avvalphen/domains/avvalphen.org/public_html/humhub/protected/modules/tracker/controllers/services/IssueEditor.php:55\n\nStack trace:\n#0 /home/avvalphen/domains/avvalphen.org/public_html/humhub/protected/modules/tracker/controllers/IssueController.php(128): tracker\\controllers\\services\\IssueEditor-&gt;__construct(Object(tracker\\models\\Issue))\n#1 [internal function]: tracker\\controllers\\IssueController-&gt;actionEdit(&#039;1&#039;)\n#2 /home/avvalphen/domains/avvalphen.org/public_html/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)\n#3 /home/avvalphen/domains/avvalphen.org/public_html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\\base\\InlineAction-&gt;runWithParams(Array)\n#4 /home/avvalphen/domains/avvalphen.org/public_html/humhub/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\\base\\Controller-&gt;runAction(&#039;edit&#039;, Array)\n#5 /home/avvalphen/domains/avvalphen.org/public_html/humhub/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\\base\\Module-&gt;runAction(&#039;tracker-issues/...&#039;, Array)\n#6 /home/avvalphen/domains/avvalphen.org/public_html/humhub/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\\web\\Application-&gt;handleRequest(Object(humhub\\components\\Request))\n#7 /home/avvalphen/domains/avvalphen.org/public_html/humhub/index.php(25): yii\\base\\Application-&gt;run()\n#8 {main}</pre>",
        "status": 500,
        "statusText": "Internal Server Error"
    },
    "html": "<pre>Exception &#039;LogicException&#039; with message &#039;&#039; \n\nin /home/avvalphen/domains/avvalphen.org/public_html/humhub/protected/modules/tracker/controllers/services/IssueEditor.php:55\n\nStack trace:\n#0 /home/avvalphen/domains/avvalphen.org/public_html/humhub/protected/modules/tracker/controllers/IssueController.php(128): tracker\\controllers\\services\\IssueEditor-&gt;__construct(Object(tracker\\models\\Issue))\n#1 [internal function]: tracker\\controllers\\IssueController-&gt;actionEdit(&#03...",
    "error": {},
    "errorThrown": "Internal Server Error",
    "validationError": false
}

**Comment by githubjeka** [comment]
see for https://github.com/githubjeka/tracker-issues/issues/8

Now "minVersion" for HumHub "1.2.3"
