### ISSUE TITLE
Unninstall doesn't work correctly

### ISSUE THREAD

**Issue by githubjeka** [githubjeka/tracker-issues#2]
rel #1

**Comment by solracsf** [comment]
Object from SQL

![image](https://cloud.githubusercontent.com/assets/12234510/24398295/4a2430e8-13a9-11e7-970e-5c5f8d0b6c74.png)

Shouldn't these be deleted if module is uninstalled?

**Comment by githubjeka** [comment]
I have not configured these things yet ...

**Comment by solracsf** [comment]
Ok. 

Also attached files should be deleted.

![image](https://cloud.githubusercontent.com/assets/12234510/24398448/bcd63334-13a9-11e7-9d6c-a2fd21008209.png)

You should publish this as a pre-alpha-release :)
