### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by spoorun** [githubjeka/tracker-issues#21]
Tried installing on both the SaaS version and a self-hosted version.
Both times it installed, but when enabled:
a) the Dashboard stream ceased to work ('Stream could not be initialised!')
b) opening the app itself gives this error: 'Class 'humhub\modules\dashboard\components\actions\DashboardStream' not found'

**Comment by spoorun** [comment]
Error: Class 'humhub\modules\dashboard\components\actions\DashboardStream' not found in /xxx/htdocs/humhub/protected/modules/tracker/controllers/actions/DashboardStreamAction.php:12
Stack trace:
#0 /xxx/htdocs/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(293): include()
#1 [internal function]: yii\BaseYii::autoload('tracker\\control...')
#2 /xxx/htdocs/humhub/protected/modules/tracker/controllers/DashboardController.php(22): spl_autoload_call('tracker\\control...')
#3 /xxx/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(225): tracker\controllers\DashboardController->actions()
#4 /xxx/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(126): yii\base\Controller->createAction('issues')
#5 /xxx/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('issues', Array)
#6 /xxx/htdocs/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('tracker-issues/...', Array)
#7 /xxx/htdocs/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request))
#8 /xxx/htdocs/humhub/index.php(25): yii\base\Application->run()
#9 {main}

**Comment by spoorun** [comment]
The same errors occur if the module is activated within a space.

**Comment by githubjeka** [comment]
The code is old by [trace](https://github.com/githubjeka/tracker-issues/issues/21#issuecomment-451656062). Try to install[ last release ](https://github.com/githubjeka/tracker-issues/releases/tag/v0.2.1)

**Comment by githubjeka** [comment]
Thanks for issue. Try it now.
