### ISSUE TITLE
Задачи не отображаются в списке задач

### ISSUE THREAD

**Issue by psychedel** [githubjeka/tracker-issues#23]
Список пуст при любых фильтрах, при этом при составлении задачи ошибок не отображается и на нее можно получить постоянную ссылку.
В списке при этом она все равно не находится.
В чем может быть дело

Версия: 0.2.2
humhub 1.3.14 (на 1.3.13 была таже проблема)

Спасибо!

**Comment by githubjeka** [comment]
А как вам удаётся получить прямую ссылку, если вы не видите задачи?

**Comment by psychedel** [comment]
Задачи же создаются - после того как я их создал, я вижу задачу и могу получить на нее ссылку.
Вот в списке они не находятся и не отображаются (с любыми фильтрами, как личные так и групповые). Я начинаю думать может с правами какая-то проблема (у меня humhub в облаке), но пока еще не понял в чем действительно причина.

**Comment by psychedel** [comment]
Есть информация о ZendSearch\Lucene\Exception\RuntimeException
в humhub панель администратора -> информация -> аудит.

`ZendSearch\Lucene\Exception\RuntimeException: fopen(/var/www/html/protected/runtime/searchdb/read.lock.file): failed to open stream: Permission denied in /var/www/html/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Storage/File/Filesystem.php:55 Stack trace: #0 /var/www/html/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Storage/Directory/Filesystem.php(172): ZendSearch\Lucene\Storage\File\Filesystem->__construct('/var/www/html/p...', 'w+b') #1 /var/www/html/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/LockManager.php(118): ZendSearch\Lucene\Storage\Directory\Filesystem->createFile('read.lock.file') #2 /var/www/html/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Index.php(380): ZendSearch\Lucene\LockManager::obtainReadLock(Object(ZendSearch\Lucene\Storage\Directory\Filesystem)) #3 /var/www/html/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Lucene.php(56): ZendSearch\Lucene\Index->__construct('/var/www/html/p...', true) #4 /var/www/html/protected/humhub/modules/search/engine/ZendLuceneSearch.php(352): ZendSearch\Lucene\Lucene::create('/var/www/html/p...') #5 /var/www/html/protected/humhub/modules/search/engine/ZendLuceneSearch.php(169): humhub\modules\search\engine\ZendLuceneSearch->getIndex() #6 /var/www/html/protected/humhub/modules/directory/controllers/DirectoryController.php(105): humhub\modules\search\engine\ZendLuceneSearch->find('', Array) #7 [internal function]: humhub\modules\directory\controllers\DirectoryController->actionMembers() #8 /var/www/html/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #9 /var/www/html/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #10 /var/www/html/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('members', Array) #11 /var/www/html/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('directory/direc...', Array) #12 /var/www/html/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #13 /var/www/html/index.php(25): yii\base\Application->run() #14 {main} 
`
И такое Info 
(host, IP я вырезал из лога)

`Info  Mon, 01 Jul 2019 14:15:45 +0100  application
$_GET = [ 'r' => 'directory/directory/members' ] $_SERVER = [ 'HTTP_HOST' => '' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0' 'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' 'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.5' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate' 'HTTP_CONNECTION' => 'keep-alive' 'HTTP_REFERER' => 'http://''/index.php?r=tracker-issues%2Ftag%2Findex' 'HTTP_COOKIE' => 'language=1a5d2974ea917978601442bedaf0e2f38a99b7c830e0e2bddf842f0e008cad0fa%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22ru%22%3B%7D; PHPSESSID=ueie4ro3kphost15k4dmn8ielc; _csrf=6a6a18280f9bdcda158ae0e8d2e5841aceff8602395d30d67de6d9576f88d0cea%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%227Vi0cZ2dt3WEWufs5L9d3Mb_8kdO1ink%22%3B%7D; _identity=83b88056aed6545f051bdb9d41dd67058b9be66dbb21b9a9b8ca1901b92a9660a%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B1%2C%225e52b3ef-82d7-42da-b737-639a2583a47c%22%2C2592000%5D%22%3B%7D; pm_getting-started-panel=expanded; pm_panel-activities=expanded; pm_new-people-panel=expanded; pm_user-statistics-panel=expanded; pm_new-spaces-panel=expanded; pm_spaces-statistics-panel=expanded' 'HTTP_UPGRADE_INSECURE_REQUESTS' => '1' 'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' 'SERVER_SIGNATURE' => '<address>Apache/2.4.29 (Ubuntu) Server at '' Port 80</address> ' 'SERVER_SOFTWARE' => 'Apache/2.4.29 (Ubuntu)' 'SERVER_NAME' => '' 'SERVER_ADDR' => '10.0.0.4' 'SERVER_PORT' => '80' 'REMOTE_ADDR' => '91.187.67.180' 'DOCUMENT_ROOT' => '/var/www/html' 'REQUEST_SCHEME' => 'http' 'CONTEXT_PREFIX' => '' 'CONTEXT_DOCUMENT_ROOT' => '/var/www/html' 'SERVER_ADMIN' => 'webmaster@localhost' 'SCRIPT_FILENAME' => '/var/www/html/index.php' 'REMOTE_PORT' => '56929' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'REQUEST_METHOD' => 'GET' 'QUERY_STRING' => 'r=directory%2Fdirectory%2Fmembers' 'REQUEST_URI' => '/index.php?r=directory%2Fdirectory%2Fmembers' 'SCRIPT_NAME' => '/index.php' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1561986945.926 'REQUEST_TIME' => 1561986945 ] `

**Comment by githubjeka** [comment]
По тексту ошибки у вас (была) проблема с правами доступа к директории файлов ZendSearch, по умолчанию - `protected/runtime/searchdb`. От чего внутренний механизм PHP ZendSearch не может в эту директорию сохранить нужную ему информацию.

Это влияет только на поиск нужного пользователя в списке пользователей. На текущий модуль tracker-issues это не должно влиять.

От имени какого пользователя вы смотрите список задач? Под глобальным администратором пробовали?

**Comment by psychedel** [comment]
Да, конечно - я пробовал от глобального администратора и от пользователя.
Но в остальном я только начинаю разбираться с HumHub, наверное мог упустить что-то элементарное.
Сегодня вечером планирую вплотную заняться этой проблемой.
Если вы знаете какую информацию из логов я мог бы показать что бы уточнить ситуацию - могло бы тоже помочь. Спасибо!

**Comment by psychedel** [comment]
Прошу извинить за введение в заблуждение - оказывается задачи не отображались т.к. срок не был до конца определен и не стоял этот фильтр в списке задач.
