### ISSUE TITLE
Submit module to marketplace

### ISSUE THREAD

**Issue by spoorun** [githubjeka/tracker-issues#35]
It would be great if this were available easily to users via the marketplace, if that's possible?
Many thanks

**Comment by githubjeka** [comment]
nothing is impossible

**Comment by spoorun** [comment]
Bounty issued $40. Hopefully others will add to this too.

https://www.bountysource.com/issues/90287005-submit-module-to-marketplace

**Comment by vporton** [comment]
What is the marketplace?

**Comment by githubjeka** [comment]
https://www.humhub.com/en/marketplace

**Comment by githubjeka** [comment]
https://www.humhub.com/en/marketplace/tracker_issue/

**Comment by spoorun** [comment]
@githubjeka Thanks for sorting that.
1) The bounty is still unclaimed that we posted :D for you, not a lot, but maybe a takeway  or two :D
2) It is now in the Marketplace, but it is not appearing from within the app so can't be added, is there some extra work or authorisation/approval that is required still?

**Comment by spoorun** [comment]
> @githubjeka Thanks for sorting that.
> 
>     1. The bounty is still unclaimed that we posted :D for you, not a lot, but maybe a takeway  or two :D
> 
>     2. It is now in the Marketplace, but it is not appearing from within the app so can't be added, is there some extra work or authorisation/approval that is required still?

Hi @githubjeka the module is still not available in marketplace to install inside an app, so can we reopen this until that's sorted thanks. Do you know the reason for that not working?

**Comment by spoorun** [comment]
> > @githubjeka Thanks for sorting that.
> > ```
> > 1. The bounty is still unclaimed that we posted :D for you, not a lot, but maybe a takeway  or two :D
> > 
> > 2. It is now in the Marketplace, but it is not appearing from within the app so can't be added, is there some extra work or authorisation/approval that is required still?
> > ```
> 
> Hi @githubjeka the module is still not available in marketplace to install inside an app, so can we reopen this until that's sorted thanks. Do you know the reason for that not working?

Just seen your post on Bountysource, that discussions are underway to get the module installable within the app.
Many thanks
