### ISSUE TITLE
throws errors after being installed and activated from the marketplace

### ISSUE THREAD

**Issue by xdCL** [githubjeka/tracker-issues#36]
Hello, thank you very much for reading this, your work with this module is great, when installing and activating it as requested from the marketplace, it instantly throws me this string of errors:

`ERROR  Sun, 06 Sep 2020 11:51:03 -0700 yii\base\UnknownPropertyExceptionyii\base\UnknownPropertyException: Getting unknown property: tracker\models\IssueContent::user in /MY-HH/INSTALLATION/PATH/protected/vendor/yiisoft/yii2/base/Component.php:154 Stack trace: #0 /MY-HH/INSTALLATION/PATH/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(298): yii\base\Component->__get('user') #1 /MY-HH/INSTALLATION/PATH/protected/modules/tracker_issue/views/issue/__item_index.php(54): yii\db\BaseActiveRecord->__get('user') #2 /MY-HH/INSTALLATION/PATH/protected/vendor/yiisoft/yii2/base/View.php(348): require('/MY-HH/INSTALLATION/...') #3 /MY-HH/INSTALLATION/PATH/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/MY-HH/INSTALLATION/...', Array) #4 /MY-HH/INSTALLATION/PATH/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/MY-HH/INSTALLATION/...', Array, NULL) #5 /MY-HH/INSTALLATION/PATH/protected/vendor/yiisoft/yii2/widgets/ListView.php(191): yii\base\View->render('__item_index', Array) #6 /MY-HH/INSTALLATION/PATH/protected/vendor/yiisoft/yii2/widgets/ListView.php(124): yii\widgets\ListView->renderItem(Object(tracker\models\Issue), 1, 0) #7 /MY-HH/INSTALLATION/PATH/protected/vendor/yiisoft/yii2/widgets/BaseListView.php(160): yii\widgets\ListView->renderItems() #8 /MY-HH/INSTALLATION/PATH/protected/vendor/yiisoft/yii2/widgets/BaseListView.php(135): yii\widgets\BaseListView->renderSection('{items}') #9 [internal function]: yii\widgets\BaseListView->yii\widgets\{closure}(Array) #10 /MY-HH/INSTALLATION/PATH/protected/vendor/yiisoft/yii2/widgets/BaseListView.php(138): preg_replace_callback('/{\\w+}/', Object(Closure), '{summary}\n{item...') #11 /MY-HH/INSTALLATION/PATH/protected/vendor/yiisoft/yii2/base/Widget.php(140): yii\widgets\BaseListView->run() #12 /MY-HH/INSTALLATION/PATH/protected/modules/tracker_issue/views/issue/__index.php(24): yii\base\Widget::widget(Array) #13 /MY-HH/INSTALLATION/PATH/protected/vendor/yiisoft/yii2/base/View.php(348): require('/MY-HH/INSTALLATION/...') #14 /MY-HH/INSTALLATION/PATH/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/MY-HH/INSTALLATION/...', Array) #15 /MY-HH/INSTALLATION/PATH/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/MY-HH/INSTALLATION/...', Array, NULL) #16 /MY-HH/INSTALLATION/PATH/protected/modules/tracker_issue/views/issue/list.php(59): yii\base\View->render('__index', Array) #17 /MY-HH/INSTALLATION/PATH/protected/vendor/yiisoft/yii2/base/View.php(348): require('/MY-HH/INSTALLATION/...') #18 /MY-HH/INSTALLATION/PATH/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/MY-HH/INSTALLATION/...', Array) #19 /MY-HH/INSTALLATION/PATH/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/MY-HH/INSTALLATION/...', Array, Object(tracker\controllers\DashboardController)) #20 /MY-HH/INSTALLATION/PATH/protected/vendor/yiisoft/yii2/base/Controller.php(409): yii\base\View->render('/issue/list', Array, Object(tracker\controllers\DashboardController)) #21 /MY-HH/INSTALLATION/PATH/protected/modules/tracker_issue/controllers/DashboardController.php(42): yii\base\Controller->render('/issue/list', Array) #22 [internal function]: tracker\controllers\DashboardController->actionIssues(true) #23 /MY-HH/INSTALLATION/PATH/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #24 /MY-HH/INSTALLATION/PATH/protected/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array) #25 /MY-HH/INSTALLATION/PATH/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('issues', Array) #26 /MY-HH/INSTALLATION/PATH/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('tracker-issues/...', Array) #27 /MY-HH/INSTALLATION/PATH/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #28 /MY-HH/INSTALLATION/PATH/index.php(25): yii\base\Application->run() #29 {main}`

Best regards.

**Comment by githubjeka** [comment]
Hello. Which version of Humhub are you using?
