### ISSUE TITLE
New Module icon

### ISSUE THREAD

**Issue by luke-** [githubjeka/tracker-issues#37]
We have created two possible module icons. What do you think about them?   

https://user-images.githubusercontent.com/62644500/96501819-3a052a00-1251-11eb-94fb-1f0b5568abfa.png

https://user-images.githubusercontent.com/62644500/96501816-396c9380-1251-11eb-9d81-451002fa6498.png

**Comment by githubjeka** [comment]
The first icon look good to me

**Comment by githubjeka** [comment]
#39
