### ISSUE TITLE
Задача все время создается

### ISSUE THREAD

**Issue by zikwall** [githubjeka/tracker-issues#4]
Заметил то, что при любом действии, если уже была нажата ссылка создать задачу, она создается, даже при клике на отмену.

**Comment by githubjeka** [comment]
This is a feature called "Draft". Now, when you click "Create issue" will be created one draft issue, and you are updating already the data for this task in fact. Later it will be improved to autosave every N secоnds when you describe your issue. For example, Jetbrain Youtrack has this behavior.

____
Эта особенность "Черновик", когда вы жмёте "Создать задачу" - сначала создаётся черновик(пустая задача) и фактически вы просто добавляете нужную информации к созданной задачи. В будущем это будет улучшено до автосохранения всех данных по задаче каждые N секунд, пока вы вводите данные по задаче. Многие вещи берутся как аналоги из коммерческих успешных проектов, например, JetBrain Youtrack имеет такую особенность - создаётся черновик, при клике "Create issue".
