### ISSUE TITLE
Cannot disable by default 

### ISSUE THREAD

**Issue by blackPantherOS** [githubjeka/tracker-issues#44]
Hi, 
I tried this module  but I can't disable by default for groups and users, always show on menubar and available for all user. 
![blackPanther_20210130_090353](https://user-images.githubusercontent.com/12883566/106351072-16cf2980-62da-11eb-8b9f-d8e3ed18338c.jpg)

While deactivated for all!
![blackPanther_20210130_090704](https://user-images.githubusercontent.com/12883566/106351128-978e2580-62da-11eb-82cd-7a2556217630.jpg)

Possible fix it ?

**Comment by ArchBlood** [comment]
Just putting it out there that deactivated isn't the same as disabling the possibility of enabling a module

**Comment by blackPantherOS** [comment]
Hi, something mistake happend! Sorry... want to use this module, userful for me, but for specified group only. But always displayed on the menu bar for all users who are members of our social web. Possible that menu items of tracker not showing always?

**Comment by githubjeka** [comment]
To quick fix - added ability to hide items of top menu.

Add in `protected/config/web.php` file this code:

```php
<?php
/**
 * This file provides to overwrite the default HumHub / Yii configuration by your local Web environments
 * @see http://www.yiiframework.com/doc-2.0/guide-concept-configurations.html
 * @see http://docs.humhub.org/admin-installation-configuration.html
 * @see http://docs.humhub.org/dev-environment.html
 */
return [
    'modules' => [
        'tracker-issues' => [
            'showOnTopMenu' => false,
        ]
    ]
];
```



P.S. The new version in Marketplace must first be checked and approved by Humhubs staff. This can take up to 3 working days.

**Comment by blackPantherOS** [comment]
"
> To quick fix - added ability to hide items of top menu.
`
> 
> P.S. The new version in Marketplace must first be checked and approved by Humhubs staff. This can take up to 3 working days."

thank you so much, i will try soon...
