### ISSUE TITLE
Ошибка при создании задачи / Error creating task

### ISSUE THREAD

**Issue by zikwall** [githubjeka/tracker-issues#6]
Здравствуйте! Решил обновиться все вроде бы хорошо, была даже эта [ошибка](https://github.com/githubjeka/tracker-issues/issues/5), все норм. Но когда хочу создать задачу выскакивает ошибка: **Invalid argument supplied for foreach()**

---

Hello! I decided to update everything seems to be good, there was even this [error] (https://github.com/githubjeka/tracker-issues/issues/5), all the norms. But when I want to create a task I get an error:: **Invalid argument supplied for foreach()**

```

{
    "url": "/s/dobro-pozhalovat-v-prostranstvo/tracker-issues/issue/create",
    "status": 500,
    "response": "<pre>PHP Warning: yii\\base\\ErrorException with message Invalid argument supplied for foreach(); \n\ninC:\\OpenServer\\domains\\ais\\protected\\humhub\\modules\\content\\models\\Content.php:166 Stack trace:\n#0...<pre>",
    "textStatus": "error",
    "dataType": "html",
    "xhr": {
        "readyState": 4,
        "responseText": "<pre>PHP Warning: yii\\base\\ErrorException&#039; with message Invalid argument supplied for foreach(); \n\ninC:\\OpenServer\\domains\\ais\\protected\\humhub\\modules\\content\\models\\Content.php:166\n\n Stack trace:\n#0 ...</pre>",
        "status": 500,
        "statusText": "Internal Server Error"
    },
    "html": "<pre>PHP Warning: yii\\base\\ErrorException with message Invalid argument supplied for foreach() \n\nin C:\\OpenServer\\domains\\ais\\protected\\humhub\\modules\\content\\models\\Content.php:166\n\nStack trace:\n#0 C:\\OpenServer\\domains\\ais\\protected\\humhub\\modules\\content\\models\\Content.php(166): yii\\base\\ErrorHandler-&gt;handleError(2, &#039;Invalid argumen...&#039;, &#039;C:\\\\OpenAir\\\\Open...&#039;, 166, Array)\n#1 C:\\OpenServer\\domains\\ais\\protected\\vendor\\yiiso...",
    "error": {},
    "errorThrown": "Internal Server Error",
    "validationError": false
}

```

**Comment by githubjeka** [comment]
After merge of https://github.com/humhub/humhub/pull/2497 this error will be fixed 100%

**Comment by githubjeka** [comment]
Sorry for that. [Module requere Humhub 1.2.1](https://github.com/githubjeka/tracker-issues/blob/master/module.json#L13) which is in development...

To quick fix this issue you can replace this files manualy:
- [humhub/protected/humhub/modules/content/models/Content.php](https://github.com/githubjeka/humhub/blob/00987e4c0229585b07a3638e074acc12be8e1587/protected/humhub/modules/content/models/Content.php)
- [humhub/protected/humhub/modules/content/notifications/ContentCreated.php](https://github.com/githubjeka/humhub/blob/00987e4c0229585b07a3638e074acc12be8e1587/protected/humhub/modules/content/notifications/ContentCreated.php)

----------------

Извиняюсь за эту проблему, я использую свой форк Humhub, в котором уже эта ошибка исправлена. Пока висит запрос на обновление реального Humhub вы можете исправить это, заменив содержимое двух файлов, указанных выше.

**Comment by zikwall** [comment]
Спасибо это заработало!:)
Заметил еще одну проблему при  добавлении подзадач, добавлении номенклатуры и завершении задачи выходит одна и та же ошибка (статус 302) и во время этого перезагружается страница, не могу уловить ее, но написано там:

---

Thanks it earned! :)
I noticed one more problem when adding subtasks, adding the nomenclature and completing the task, the same error occurs (status 302) and during this the page reloads, I can not catch it, but it is written there:

```

error: "Found"

```

При добавлении подзадачи - задача сохраняется как черновик
При добавлении номенклатуры - номенклатура добавляется, но с выводом этой ошибки
При завершении работы - тоже самое, что и с добавлением номенклатуры, задача завершается, но эта ошибка выходит

Думаю, что это связано с вашей версией Humhub...
Прикрепляю изображения, заранее прошу прощения - это все, что я успел запечатлеть

---

When adding a subtask - the task is saved as a draft
When adding an tag - the nomenclature is added, but with the output of this error
At the end of work - the same as with the addition of the tag, the task is completed, but this error leaves.

I think that this is due to your version of Humhub ...
I attach the images:

![2017-05-04_16-31-05](https://cloud.githubusercontent.com/assets/23422968/25706069/0d2763de-30e8-11e7-947e-9765549ba087.jpg)
![2017-05-04_16-32-23](https://cloud.githubusercontent.com/assets/23422968/25706070/0d38dc54-30e8-11e7-99e9-8304ae0162a8.jpg)

**Comment by githubjeka** [comment]
Попробуйте очистить папку `your-humhub-app/assets/`

**Comment by zikwall** [comment]
@githubjeka да, чистил и `protected/runtime/cache/` чистил 

---

Yes, cleaned and `protected/runtime/cache/` also cleaned

**Comment by githubjeka** [comment]
Ок попробую воспроизвести.

**Comment by githubjeka** [comment]
Там действительно была одна и та же ошибка js при перечисленных случаях.
Пофикшено тремя разными способами, предоставленными Humhub. Посмотрим со временем какой лучше себя зарекомендует )
