### ISSUE TITLE
Create new issue = Error

### ISSUE THREAD

**Issue by solracsf** [githubjeka/tracker-issues#8]
`yii\base\ErrorException: Invalid argument supplied for foreach() in /protected/humhub/modules/content/models/Content.php:166`

Latest HumHub master.

**Comment by githubjeka** [comment]
Reference :/
https://github.com/githubjeka/tracker-issues/issues/6#issuecomment-299178983

**Comment by solracsf** [comment]
Sorry but russian topics, i just don't open them as i don't understand the subject...

Maybe put that on the install instructions?

**Comment by githubjeka** [comment]
After merge of humhub/humhub#2497 this error will be fixed 100%

To quick fix this issue you can replace this files manualy:
- [humhub/protected/humhub/modules/content/models/Content.php](https://github.com/githubjeka/humhub/blob/00987e4c0229585b07a3638e074acc12be8e1587/protected/humhub/modules/content/models/Content.php)
- [humhub/protected/humhub/modules/content/notifications/ContentCreated.php](https://github.com/githubjeka/humhub/blob/00987e4c0229585b07a3638e074acc12be8e1587/protected/humhub/modules/content/notifications/ContentCreated.php)

**Comment by solracsf** [comment]
Does 5c034c2e00ba0e08c20baf2715befb4739d25289 fixes this (without having to merge those files)?

**Comment by githubjeka** [comment]
No, this issue will be closed when something will be decided in https://github.com/humhub/humhub/pull/2497
